# Generated by Django 3.1.7 on 2021-05-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayments',
            old_name='subscription_name',
            new_name='plan_name',
        ),
    ]
