# Generated by Django 3.1.7 on 2021-05-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210530_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayments',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
