# Generated by Django 3.1.7 on 2021-02-22 12:07

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.FileField(upload_to='')),
                ('web_page', models.URLField()),
                ('broker_line', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='solution',
            name='context',
            field=models.CharField(max_length=350),
        ),
        migrations.CreateModel(
            name='BankCombinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeffiecient', models.FloatField(default=0)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bank')),
                ('challange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.challange')),
                ('solution', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='challange', chained_model_field='challange', on_delete=django.db.models.deletion.CASCADE, to='core.solution')),
            ],
        ),
    ]
