# Generated by Django 3.1.7 on 2021-02-22 12:35

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210222_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcombinations',
            name='solution',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='challange', chained_model_field='challange', on_delete=django.db.models.deletion.CASCADE, to='core.solution', unique=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='challange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.challange'),
            preserve_default=False,
        ),
    ]
