# Generated by Django 3.1.7 on 2021-03-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210303_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcombinations',
            name='coeffiecient',
            field=models.FloatField(),
        ),
    ]
