# Generated by Django 3.1.7 on 2021-04-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20210419_1418'),
        ('core', '0006_auto_20210304_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='solution',
            old_name='context',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bankcombinations',
            name='challange',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='challange',
        ),
        migrations.AlterField(
            model_name='bank',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bankcombinations',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='core.bank'),
        ),
        migrations.AlterField(
            model_name='bankcombinations',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.solution'),
        ),
        migrations.DeleteModel(
            name='Challange',
        ),
        migrations.AddField(
            model_name='bankcombinations',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.challenge'),
        ),
        migrations.AddField(
            model_name='solution',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='core.challenge'),
        ),
    ]
