# Generated by Django 3.1.7 on 2021-04-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210422_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcombinations',
            name='solution',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.TextField(),
        ),
    ]
