# Generated by Django 3.1.7 on 2021-05-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210423_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcombinations',
            old_name='coeffiecient',
            new_name='coefficient',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='challenge',
        ),
        migrations.AlterField(
            model_name='bank',
            name='broker_line',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bank',
            name='web_page',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bankcombinations',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_combinations', to='core.challenge'),
        ),
    ]
