# Generated by Django 3.1.7 on 2021-05-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210502_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(error_messages={'unique': 'Bank with this name already exists'}, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='web_page',
            field=models.URLField(error_messages={'unique': 'Bank with this web page already exists'}, unique=True),
        ),
    ]
