# Generated by Django 3.1.7 on 2021-05-04 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210504_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcombinations',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combination', to='core.challenge'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(error_messages={'unique': 'Challenge with this name already exists'}, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.TextField(error_messages={'unique': 'Solution with this name already exists'}, unique=True),
        ),
    ]
