# Generated by Django 3.1.7 on 2021-05-31 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210530_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcombinations',
            name='coefficient',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
