# Generated by Django 3.1.7 on 2021-06-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210531_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcombinations',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_combinations', to='core.challenge'),
        ),
        migrations.AlterField(
            model_name='bankcombinations',
            name='coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
