# Generated by Django 3.1.7 on 2021-03-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210303_1021'),
        ('clients', '0002_auto_20210303_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='bank_combinations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broker_result', to='core.bankcombinations'),
        ),
        migrations.AddField(
            model_name='clients',
            name='challanges',
            field=models.ManyToManyField(to='core.Challange'),
        ),
    ]
