# Generated by Django 3.1.7 on 2021-03-03 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210303_1021'),
        ('clients', '0003_auto_20210303_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='challanges',
        ),
        migrations.CreateModel(
            name='ClientChallangeAndSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.challange')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clients')),
                ('solution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.solution')),
            ],
        ),
    ]
