# Generated by Django 3.1.7 on 2021-03-04 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210303_1021'),
        ('clients', '0008_auto_20210303_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_matches', models.ManyToManyField(blank=True, to='core.BankCombinations')),
                ('challange', models.ManyToManyField(blank=True, to='core.Challange')),
            ],
        ),
        migrations.RemoveField(
            model_name='clients',
            name='bank_combinations',
        ),
        migrations.DeleteModel(
            name='ClientChallangeAndSolution',
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clients'),
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='solution',
            field=models.ManyToManyField(blank=True, to='core.Solution'),
        ),
    ]
