# Generated by Django 3.1.7 on 2021-04-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20210304_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienthistory',
            name='best_matches',
        ),
        migrations.RemoveField(
            model_name='clienthistory',
            name='challange',
        ),
    ]
