# Generated by Django 3.1.7 on 2021-04-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20210419_1418'),
        ('core', '0007_auto_20210419_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthistory',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_challenge', to='core.challenge'),
        ),
        migrations.AddField(
            model_name='clients',
            name='best_matches',
            field=models.ManyToManyField(blank=True, to='core.BankCombinations'),
        ),
        migrations.RemoveField(
            model_name='clienthistory',
            name='solution',
        ),
        migrations.AddField(
            model_name='clienthistory',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_solutions', to='core.solution'),
        ),
    ]
