# Generated by Django 3.1.7 on 2021-05-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20210523_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienthistory',
            name='combinations',
        ),
        migrations.AddField(
            model_name='clients',
            name='combinations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
