# Generated by Django 3.1.7 on 2021-06-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210531_0608'),
        ('clients', '0016_auto_20210523_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienthistory',
            name='challenge',
            field=models.ForeignKey(blank=True, default='deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.challenge'),
        ),
        migrations.AlterField(
            model_name='clienthistory',
            name='solution',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
